### ISSUE TITLE
is_Distname excludes UTF8 characters entirely.

### ISSUE THREAD

**Issue by kentfredric** [rjbs/MooseX-Types-Perl#2]
I posit that 
-  `Acme-♭`
- `Acme-ಠ_ಠ`

Should both be considered valid dist names, albeit unusual distnames.

Or at least, these could be included under the still hypothetical LaxDistName type.

/cc @karenetheridge

**Comment by karenetheridge** [comment]
Yes they should.  Ultimately this needs to be fixed in Params::Util, as that's from where this module derives its type definition.

here are some of the notes I've scribbled, that I'm blatting here for the audience:

http://www.gossamer-threads.com/lists/perl/porters/272296:

    A valid class name, as far as the left side of -> is concerned, is either
    something that is already in the stash cache hash, and failing that,
    something that has a IO slot, and failing that, something that matches
    /^[\p{XIDS}_]/.

other sources suggest an identifier is  `/^\p{ID_Start}\p{ID_Continue}+/`

    A punctuation character should
    not be in the middle of an identifier, so Perl uses a slightly
    modified version of ID Continue.  Perl's version requires an IDCont
    character to also match \w.

And: "perldata specifies fairly precisely the rules in effect."

**Comment by karenetheridge** [comment]
And then my notes say... "Yup, perldelta in 5.18+ clearly specifies the rules... and it isn't at all simple, and all the above sources are wrong." :)

**Comment by rjbs** [comment]
Don't conflate distributions and packages.  Andreas has said on multiple occasions that PAUSE distributions will remain ASCII-only.

If there are specific changes to PackageName or ModuleName to review in the future, I'll do that when they are proposed.
